Remove com.mountainminds.eclemma.feature.feature.group
as it conflicts with org.eclipse.eclemma.feature.feature.group, which
appears to be included by default in Oxygen. So if you use Neon, you
would have to manually install eclemma now... but at least using Oxygen
is no longer completely broken.

  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the
following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Old EclEmma version
(com.mountainminds.eclemma) cannot be installed together with new
(org.eclipse.eclemma). Uninstall currently installed version and try the
install again. 3.0.0.201701271646 (com.mountainminds.eclemma.core
3.0.0.201701271646)
    ERROR: org.eclipse.equinox.p2.director code=0 EclEmma Core
2.3.3.201602231923 (com.mountainminds.eclemma.core 2.3.3.201602231923)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root
1.0.0.v1492077664535
    ERROR: org.eclipse.equinox.p2.director code=0 To:
com.mountainminds.eclemma.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root
1.0.0.v1492077664535
    ERROR: org.eclipse.equinox.p2.director code=0 To:
org.eclipse.eclemma.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: EclEmma Java
Code Coverage 2.3.3.201602231923
(com.mountainminds.eclemma.feature.feature.group 2.3.3.201602231923)
    ERROR: org.eclipse.equinox.p2.director code=0 To:
com.mountainminds.eclemma.core [2.3.3.201602231923]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy
dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: EclEmma Java
Code Coverage 3.0.0.201701271646
(org.eclipse.eclemma.feature.feature.group 3.0.0.201701271646)
    ERROR: org.eclipse.equinox.p2.director code=0 To: bundle
com.mountainminds.eclemma.core [3.0.0.201701271646]

Change-Id: I743e89eafb05e797172b9fec6bef24e712add4bd
Signed-off-by: Michael Vorburger <vorburger@redhat.com>